[package]
name = "owldb"
version = "0.1.0"
edition = "2021"

[lib]
name = "owldb"
path = "src/lib.rs"

[[bench]]
name = "run"
harness = false

[dependencies]
bson = "2.6.1"
criterion = "0.5.1"
env_logger = "0.10.0"
log = "0.4.20"
tokio = { version = "1.32.0", features = ["full"] }
