name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      runTests:
        description: 'Run tests'
        required: false
        default: 'true'
      runBenchmarks:
        description: 'Run benchmarks'
        required: false
        default: 'false'


env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache target
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-target-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-target-

    - name: Build
      run: cargo build --verbose
      
    - name: Tests
      run: cargo test --verbose
      if: github.event.inputs.runTests == 'true'
    
    - name: Benchmarks
      run: cargo bench --verbose
      if: github.event.inputs.runBenchmarks == 'true'

